file:C:/Install/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Install/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Install/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Install/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Install/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Install/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Install/Git/etc/gitconfig	http.sslcainfo=C:/Install/Git/mingw64/etc/ssl/certs/ca-bundle.crt
file:C:/Install/Git/etc/gitconfig	core.autocrlf=true
file:C:/Install/Git/etc/gitconfig	core.fscache=true
file:C:/Install/Git/etc/gitconfig	core.symlinks=false
file:C:/Install/Git/etc/gitconfig	pull.rebase=false
file:C:/Install/Git/etc/gitconfig	credential.helper=manager
file:C:/Install/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Install/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/Admin/.gitconfig	core.editor="C:\Install\Microsoft VS Code\bin\code" --wait
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=git@github.com:KErushnikov/ibweb-homeworks.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
